spring:
  application:
    name: Api

server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaServer:8763/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}


#endpoints:
#  restart:
#    enabled: true
#  shutdown:
#    enabled: true
#  health:
#    sensitive: false